### ISSUE TITLE
Falco plugin?

### ISSUE THREAD

**Issue by jdbohrman** [FairwindsOps/insights-plugins#139]
My team and I are looking into Insights currently and it seems to have a lot of the things we are looking for, the only thing I would love to see is a Falco plug-in. How hard would it be to get something like that spun up? the ability to monitor runtime security events would be amazing with this tool. 

https://github.com/falcosecurity/falco

**Comment by rbren** [comment]
Thanks for reaching out!

We've been looking at Falco as a possible integration. It's definitely possible.

We'd likely rely on users to install and configure falco themselves (rather than bundling it into the insights-agent), but could create a plugin here that would gather data from falco and send it back to Insights

If you're looking to get a Falco integration done ASAP, you could also use the [custom reports API](https://insights.docs.fairwinds.com/plugins/new/). It should be as easy as querying the [Falco gRPC API](https://falco.org/docs/grpc/outputs/) and repackaging the JSON it outputs.
